# Generated by Django 5.0.2 on 2024-03-19 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=100, unique=True)),
                ('patient_name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=255)),
                ('reason_for_visit', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='static/images/')),
            ],
        ),
    ]
